# Generated by Django 2.2.12 on 2020-05-15 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siteweb', '0002_auto_20200514_1558'),
    ]

    operations = [
        migrations.AddField(
            model_name='series',
            name='arquivo_do_banner',
            field=models.FilePathField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='series',
            name='url_my_anime_list',
            field=models.URLField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='series',
            name='url_anidb',
            field=models.URLField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='series',
            name='url_crunchyroll',
            field=models.URLField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='series',
            name='url_imdb',
            field=models.URLField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='series',
            name='url_the_movie_db',
            field=models.URLField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='series',
            name='url_trakt',
            field=models.URLField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='series',
            name='url_tv_maze',
            field=models.URLField(blank=True, max_length=500),
        ),
    ]
