# Generated by Django 2.2.12 on 2020-05-15 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siteweb', '0003_auto_20200515_1508'),
    ]

    operations = [
        migrations.AlterField(
            model_name='series',
            name='arquivo_do_banner',
            field=models.FilePathField(max_length=500),
        ),
    ]
