# Generated by Django 2.2.13 on 2020-06-16 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siteweb', '0004_auto_20200515_1509'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='series',
            name='arquivo_do_banner',
        ),
        migrations.RemoveField(
            model_name='series',
            name='url_anidb',
        ),
        migrations.RemoveField(
            model_name='series',
            name='url_crunchyroll',
        ),
        migrations.RemoveField(
            model_name='series',
            name='url_imdb',
        ),
        migrations.RemoveField(
            model_name='series',
            name='url_my_anime_list',
        ),
        migrations.RemoveField(
            model_name='series',
            name='url_the_movie_db',
        ),
        migrations.RemoveField(
            model_name='series',
            name='url_trakt',
        ),
        migrations.RemoveField(
            model_name='series',
            name='url_tv_maze',
        ),
        migrations.AddField(
            model_name='series',
            name='cod_img',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='series',
            name='lista_episodes',
            field=models.TextField(blank=True),
        ),
    ]
